[package]
name = "frong-bot-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
chatgpt_rs = "1.2.3"
dotenv = "0.15.0"
poise = "0.6.1"
serenity = "0.12.4"
tokio = { version = "1", features = ["full"] }

